name: Masr Blog
pygments: true
url: 
paginate: 9
paginate_path: 'page:num'
permalink: none
host: 0.0.0.0
port: 4001
destination: ./_site
plugins:  ./_plugins
layouts:  ./_layouts
include:  ['.htaccess']
timezone: 'Asia/Shanghai'
